#!/bin/bash
#
# Check cassandra local installation.
#
# This file is to be executed on all Cassandra nodes while Cassandra is running.
# It produce a file cassandra-on-<node>-<time>.tar.gz file in current file
#

# These variables can be changed to adapt the script behavior.
#CASSANDRA_HOME=
nodetool=nodetool # Add required global option like jmx authentication
cqlsh=cqlsh       # Add required global option like CQL authentication
result_dir="cassandra-on-$(uname -n)-$(date "+%Y%m%d%H%M")"
result_file="${result_dir}.tar.gz"

function prepare_directories() {
    if [[ -e $result_file ]]; then
        rm -f "$result_file"
    fi
    if [[ -e $result_dir ]]; then
        rm -fr "$result_dir"
    fi
    mkdir -p "$result_dir"
}

function find_cassandra() {
    if [[ -z $CASSANDRA_HOME ]]; then
        echo "Cassandra HOME not found be set CASSANDRA_HOME variable at the begin of the script or in the environnement" >&2
        exit 1
    fi
}

function copy_config() {
    local conf_dir="${result_dir}/conf"
    mkdir -p "$conf_dir"

    cp $CASSANDRA_HOME/conf/cassandra.yaml "${conf_dir}"
    cp $CASSANDRA_HOME/conf/cassandra-env.sh "${conf_dir}"
}


function package() {
    cd "$dest_dir"
    tar czvf "${result_file}" "${result_dir}"
}

run() {
    prepare_directories
    find_cassandra
    copy_config
    package
    echo "Cassandra checked result to be found in ${result_file}"
}

run
